# Default values for discipuli.ai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: disciplesofai/discipuli.ai
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    { cert-manager.io/cluster-issuer: "cloudlfare-letsencrypt-production" }
  hosts:
    - host: discipuli.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: discipuli.ai-tls
      hosts:
        - discipuli.ai

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
